'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Namespace DXWebApplication14

    Public Partial Class WebForm1

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' Gantt control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Gantt As Global.DevExpress.Web.ASPxGantt.ASPxGantt

        ''' <summary>
        ''' TasksDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected TasksDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

        ''' <summary>
        ''' DependenciesDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected DependenciesDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

        ''' <summary>
        ''' ResourcesDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ResourcesDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

        ''' <summary>
        ''' ResourceAssignmentsDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ResourceAssignmentsDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

        ''' <summary>
        ''' CustomTaskDetails control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected CustomTaskDetails As Global.DevExpress.Web.ASPxPopupControl

        ''' <summary>
        ''' HiddenField control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected HiddenField As Global.DevExpress.Web.ASPxHiddenField

        ''' <summary>
        ''' ASPxFormLayout1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout

        ''' <summary>
        ''' ASPxFormLayout1_E1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxFormLayout1_E1 As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' ASPxFormLayout1_E2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxFormLayout1_E2 As Global.DevExpress.Web.ASPxTrackBar

        ''' <summary>
        ''' ASPxFormLayout1_E3 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxFormLayout1_E3 As Global.DevExpress.Web.ASPxTokenBox

        ''' <summary>
        ''' ASPxFormLayout1_E4 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxFormLayout1_E4 As Global.DevExpress.Web.ASPxMemo

        ''' <summary>
        ''' ASPxFormLayout1_E5 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxFormLayout1_E5 As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' ASPxButton1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxButton1 As Global.DevExpress.Web.ASPxButton
    End Class
End Namespace
